Setup:
  Data:
    batch_size: 1000
    batch_size_test: 512
    name: mnist
    path: /proj/gpu_mtk53601/research/deq_experiments/alberto_experiment/research/data
    num_classes: 10
    subset: false
    augmentations: false
    add_random: false
    random_proj: false

  Experiment:
    description: Dense
    reversible: true
    train_ggn: true
    device: true
    seed: 42
    version: 1.0

  Model:
    feature_dim: 784
    hidden_dim: 8000
    output_dim: 10
    bias: true
    num_layers: 4
    layer_norm: false
    non_linearity: true
    inv_method: default
    inv_method_args:
      rtol: 1.0e-2
      atol: 1.0e-5

Runtime:
  Train:
    Task:
      name: classification
    args:
      num_epochs: 100
      save_checkpoint_every: 10
      steps_for_printing: 1
      log_test: true
      log_full_train: False
    loss_function:
      args:
        use_identity: true
      name: cross_entropy
    optimizer:
      args:
        lr: 0.1
        weight_decay: 0.00
      name: sgd
    scheduler:
      # name: step
    checkpoint_path: null

Output:
  Results:
    output_dir: results_mnist_n
    weight_root_dir: /proj///weights
    format_strs: ["log", "json", "csv", "tensorboard"]
